header_pages:
  - index.md   # 필요한 페이지만 남기기

# Site settings
title: "HONGDUCK"
bye_message: "Thx!"
baseurl: ""
url: "https://hongduck.github.io"
disqus: HONGDUCK

# Build settings
markdown: kramdown
permalink: /:categories/:title/
